apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-hibicode-cluster
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    labels:
      nodegroup-type: simple-workload
    ssh:
      publicKeyName: eks-hibicode
  - name: ng-scale-a
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: scale-workload
      instanceType: onDemand
    ssh:
      publicKeyName: eks-hibicode
  - name: ng-scale-b
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: scale-workload
      instanceType: onDemand
    ssh:
      publicKeyName: eks-hibicode
